### ISSUE TITLE
runtime 20.08beta

### ISSUE THREAD

**Issue by adam-rich9929** [flathub/com.github.jms55.Sandbox#1]
Tried testing app with 20.08beta runtime version but the app wouldn't run and had the error message-
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AdapterNotFound', src/main.rs:40:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by JMS55** [comment]
How do I install the 20.08beta to test it?

**Comment by bilelmoussaoui** [comment]
From flathub-beta

**Comment by JMS55** [comment]
I tested 20.08beta, works fine for me. What GPU and drivers do you have? You need something supporting vulkan.

**Comment by adam-rich9929** [comment]
sorry, didn't realise i needed vulkan
